### ISSUE TITLE
Aquí hay un problema de tipo de datos

### ISSUE THREAD

**Issue by gdeldago** [escuela-tecnica-21/ta-te-ti-JuanCanoPalacios#2]
https://github.com/escuela-tecnica-21/ta-te-ti-JuanCanoPalacios/blob/35ce1820503c788ec24a05cfc3d8c17fe38b6044/main.c#L29

Si el tipo de dato es char, no se puede utilizar strcpy (una función que copia strings). De hecho, los parámetros que espera la función son ambos de tipo string y, asi como está, el primeor es de tipo char y el segundo de tipo string. 

En ese caso se puede asignar directamente.

` tab[elc_usu] = 'X'; `

Fijate dos cosas: 1) del lado izquierdo hay algo de tipo char (una posición del vector y 2) del lado derecho hay, también, algo de tipo char (la X está con comillas simples)

¿Me explico?

Bueno, si estás de acuerdo, te toca revisar todo el programa :)

**Comment by JuanCanoPalacios** [comment]
Gracias por su tiempo profe, no me di cuenta de ese detalle
